services:
  web:
    container_name: MavanimesWrapper
    build: .
    command: bash -c "
        python --version
        && export SECRET_KEY=$(openssl rand 48 | openssl enc -A -base64)
        && python manage.py makemigrations
        && python manage.py migrate
        && python manage.py collectstatic --noinput
        && gunicorn --name mavanimes_wrapper --bind 0.0.0.0:8001 --workers 3 --timeout 120 mavanimes_wrapper.wsgi:application --log-file=/var/log/mav/gunicorn.log --access-logfile=/var/log/mav/access.log --capture-output --enable-stdio-inheritance  --log-level=info"
    volumes:
      - .:/code
      - ./staticfiles:/opt/static
      - ./log:/var/log/mav
    ports:
      - "8001:8001"
    environment:
      - PROD=True
      - STATIC_ROOT=/opt/static
    restart: unless-stopped
