# Generated by Django 4.1.4 on 2022-12-12 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.URLField(default=None, null=True)),
                ('small_image', models.URLField(default=None, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('mav_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('number', models.IntegerField(default=None, null=True)),
                ('saison', models.IntegerField(default=1, null=True)),
                ('version', models.CharField(default='VOSTFR', max_length=128, null=True)),
                ('upload_date', models.DateTimeField(default=None, null=True)),
                ('image', models.URLField(default=None, null=True)),
                ('small_image', models.URLField(default=None, null=True)),
                ('mav_url', models.URLField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='VideoURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.episode')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='tags',
            field=models.ManyToManyField(to='animes.tag'),
        ),
    ]
