# Generated by Django 4.1.4 on 2022-12-12 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='versions',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
