# Generated by Django 4.1.4 on 2022-12-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0005_alter_anime_description_alter_anime_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='value',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='versions',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
