# Generated by Django 4.1.4 on 2022-12-16 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0006_episode_value_alter_anime_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animes', to='animes.anime'),
        ),
        migrations.AlterField(
            model_name='videourl',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_urls', to='animes.episode'),
        ),
    ]
