# Generated by Django 4.1.4 on 2022-12-16 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0007_alter_episode_anime_alter_videourl_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='videourl',
            name='source',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='animes.anime'),
        ),
    ]
