# Generated by Django 4.1.4 on 2022-12-21 15:57

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0009_alter_episode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='pub_date',
            field=models.DateTimeField(default=timezone.now()),
            preserve_default=False,
        ),
    ]
