# Generated by Django 4.1.4 on 2022-12-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0012_episode_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='animes', to='animes.tag'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='type',
            field=models.CharField(blank=True, choices=[('EPISODE', 'Episode'), ('FILM', 'Film'), ('OAV', 'Oav'), ('SPECIAL', 'Special')], default='EPISODE', max_length=7),
        ),
        migrations.AlterField(
            model_name='episode',
            name='version',
            field=models.CharField(blank=True, default='VOSTFR', max_length=128),
        ),
    ]
