# Generated by Django 4.1.4 on 2022-12-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0013_alter_anime_tags_alter_episode_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='anime',
            name='mav_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
