# Generated by Django 4.1.4 on 2023-01-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0016_alter_episode_options_rename_saison_episode_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
    ]
