# Generated by Django 4.1.4 on 2023-02-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0020_rename_value_episode_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.SlugField(max_length=128),
        ),
    ]
