# Generated by Django 4.1.4 on 2023-02-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0021_alter_episode_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='type',
            field=models.CharField(blank=True, choices=[('ÉPISODE', 'Episode'), ('FILM', 'Film'), ('OAV', 'Oav'), ('SPECIAL', 'Special')], default='ÉPISODE', max_length=7),
        ),
    ]
