# Generated by Django 4.1.4 on 2023-07-17 10:06

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0023_animeimage_animeimage_unique_anime_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': [django.db.models.functions.text.Upper('name')], 'verbose_name': 'Anime', 'verbose_name_plural': 'Animes'},
        ),
        migrations.AlterModelOptions(
            name='animeimage',
            options={'ordering': ['key']},
        ),
        migrations.AlterField(
            model_name='episode',
            name='type',
            field=models.CharField(blank=True, choices=[('EPISODE', 'Episode'), ('FILM', 'Film'), ('OAV', 'Oav'), ('SPECIAL', 'Special')], default='EPISODE', max_length=7),
        ),
    ]
